export type Image = {
  media: string,
  title: string,
  thumbnail: string,
  thumb_width: number,
  thumb_height: number,
  width: number,
  height: number,
  url: string,
  _id: string,
  media_fullsize: string,
  media_preview: string,
  size: string,
  thumb_type: string,
}
